[workspace]

resolver = "2"
members = [
  "battle-of-life",
  "wasm-battle-of-life",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
# debug = true

[profile.bench]
debug = true
